## 30 Day Map Challenge 
## Day 1 : Points
## Deepak Varughese

## Loading Libraries
library(tidyverse)
library(patchwork)
library(ggtext)
library(showtext)
library(ragg)
library(here)
library(janitor)
library(sf)
library(maptiles)
library(terra)
library(tidyterra)
library(leaflet)
library(mapview)
library(rio)
library(flextable)
library(ggspatial)
library(extrafont)
font_add_google("Gochi Hand", "gochi")
font_add_google("Noto Sans")
font_add("NotoSans", regular = "path/to/NotoSans-Regular.ttf")

font_add_google("Noto Sans", "notosans")
font_add_google("Poppins", "poppins")


## Get Details of Mallapally and then save it as a .shp
##/*
##  This has been generated by the overpass-turbo wizard.
##The original search was:
##  “admin_level=10 in Mallapally”
##*/
##  [out:json][timeout:25];
##// fetch area “Mallapally” to search in
##( area["wikidata"="Q65455909"];) ->.searchArea;
##// gather results
##(
##  // query part for: “admin_level=10”
##  node["admin_level"="10"](area.searchArea);
##  way["admin_level"="10"](area.searchArea);
##  relation["admin_level"="10"](area.searchArea);
##);
##// print results
##out body;
##>;

mlply <- read_sf(here("mallapally shp", "Mallapally.shp"))


mlply_town <- mlply %>% 
  filter(Name == "Mallappally Town")


map1 <- ggplot() +
  geom_sf(data = mlply) +
  geom_sf(data = mlply_town, fill = "brown", alpha = 0.5)+
  geom_sf_text(data = mlply, aes(label = Name), size = 2.5, check_overlap = TRUE)+
  theme_void() +
  ggtitle("Mallapally Taluk", subtitle = "Mallapally is a sub-district (taluk) situated in Pathanamthitta District of the state of Kerala in India. The administrative centre of the Taluk is <b style='color:brown;'> Mallapally Town </b>. This map shows the different regions present in Mallapally Taluk.It has an estimated 130,000 residents. The river Manimala flows through the district.") +
  theme(
    panel.background = element_blank(),
    plot.title = element_textbox_simple(margin = margin(25, 45, 25, 185),
                                        family = "poppins", size = 45, color = "#1A242F"),
    plot.subtitle = element_textbox_simple(family = "poppins", size = 20, color = "#1A242F")
    ) +
  annotation_north_arrow(location = "tr",  # add north arrow to bottom-right
                         height = unit(0.5, "cm"), # size of north arrow
                         width = unit(0.5, "cm")) +
  annotation_scale(location = "bl")+
  labs(caption = "Chart: Dr. Deepak Varughese, November 2023", size = 30)


map1

ggsave("map1.jpeg", device = agg_jpeg)
