## 30 Day Map Challenge 
## Day 2 : Chloropleth
## Deepak Varughese

## Loading Libraries
library(tidyverse)
library(patchwork)
library(ggtext)
library(showtext)
library(ragg)
library(here)
library(janitor)
library(sf)
library(maptiles)
library(terra)
library(tidyterra)
library(leaflet)
library(mapview)
library(rio)
library(flextable)
library(ggspatial)
library(extrafont)
library(RColorBrewer)
font_add_google("Gochi Hand", "gochi")
font_add_google("Gochi Hand", "gochi")
showtext_auto()
##/*
##  This has been generated by the overpass-turbo wizard.
##The original search was:
##  “admin_level=10 in Mallapally”
##*/
##  [out:json][timeout:25];
##// fetch area “Mallapally” to search in
##( area["wikidata"="Q1186"];) ->.searchArea;
##// gather results
##(
##  // query part for: “admin_level=10”
##  node["admin_level"="5"](area.searchArea);
##  way["admin_level"="5"](area.searchArea);
##  relation["admin_level"="5"](area.searchArea);
##);
##// print results
##/*added by auto repair*/
##  (._;>;);
##/*end of auto repair*/
##  out body;
##>;

kl <- read_sf(here("day2_chloropleth", "Kerala shp", "kerala.shp")) %>% 
  filter(boundary == "administrative") %>% 
  mutate(name = str_remove(Name, " District")) %>% 
  select(name, geometry)


kl_pop <- import(here("day2_chloropleth","keralapop.xls")) %>% 
  clean_names() %>% 
  filter(tru=="Total") %>% 
  filter(level == "DISTRICT") %>% 
  select(name, total_population_person)


kl_pop_sf <- kl %>% 
  left_join(kl_pop, by = "name") %>% 
  select(name, total_population_person, geometry)


subtitle <- "Kerala is a State located in South India. The state has a total population of approximately 34 million. According to the 2011 Census, the most populous district in Pathanamthitta was Mallapuram with a population of approximately 4 million. This was followed by Thiruvanathapuram and Ernakulam with 3.3 and 3.2 million population respectively. Wayanad was the least populated district with a population of approximately 800,000"

title_text = "Population in Kerala"
mallapuram_data <- kl_pop_sf %>% filter(name == "Malappuram") 
mallapuram_centroid <- st_centroid(mallapuram_data$geometry)

ggplot() +
  geom_sf(data = kl_pop_sf, aes(fill = total_population_person)) +
  scale_fill_gradientn(colors = c("#FFFFE5", "#4D4D1A"), 
                       limits = range(kl_pop_sf$total_population_person),
                       labels = scales::number_format()) +
  labs(fill = "Population") +
  theme_void()+
  ggtitle("Population in Kerala", subtitle = subtitle) +
  theme(
    panel.background = element_blank(),
    plot.title = element_textbox_simple(margin = margin(35, 0, 35, 15),
                                        family = "gochi", size = 30, color = "#1A242F"),
    plot.subtitle = element_textbox_simple(margin = margin(35, 0, 45, 15),family = "gochi", size = 10, color = "#1A242F")
  ) +
  annotation_north_arrow(location = "tr",  # add north arrow to bottom-right
                         height = unit(0.5, "cm"), # size of north arrow
                         width = unit(0.5, "cm")) +
  annotation_scale(location = "bl")+
  geom_curve(aes(x = st_coordinates(mallapuram_centroid)[, 1] +0.5,
                 y = st_coordinates(mallapuram_centroid)[, 2] + 0.5,
                 xend = st_coordinates(mallapuram_centroid)[, 1],
                 yend = st_coordinates(mallapuram_centroid)[, 2]),
             arrow = arrow(length = unit(0.2, "cm")), curvature = 0.2, color = "red") +
  geom_text(aes(x = st_coordinates(mallapuram_centroid)[, 1] + 0.2,
                y = st_coordinates(mallapuram_centroid)[, 2] + 0.2),
            label = "Mallapuram", family = "gochi", size = 5, color = "red", hjust = 0, vjust = -6) +
  labs(caption = "Chart: Dr. Deepak Varughese, November 2023", size = 30)



ggsave(plot = map2, filename = "map2.jpeg", device = ragg::agg_jpeg())
